### ISSUE TITLE
uploading with --force gives two different results

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Server/anaconda-client#264] opened 2015-12-29 18:50 UTC
I originally posted this to https://github.com/Anaconda-Server/support/issues/13 But I think this is an anaconda-client issue.    So I'm re-posting here:

our CI is broken due to what looks like a new behavior/bug in `anaconda upload`

```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 -c dev --force
Using anaconda-server api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 ...
 uploaded 55 of 55Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/seaicedata
```
Same command:

```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 -c dev --force
Using anaconda-server api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 already exists ... removing
[ServerError] ('Internal server error', 500)
```

These two results toggle back and forth.

**Comment by stephenakearns** [comment] 2015-12-31 17:29
@flamingbear thanks for reporting - this was reproduced by another team member. Looking into it after the holidays.

**Comment by wojdyr** [comment] 2016-01-04 13:11
I have the same problem. As a temporary workaround I've downgraded anaconda-client:

    anaconda-client: 1.2.1-py27_0 --> 1.1.2-py27_0

**Comment by stephenakearns** [comment] 2016-01-04 16:20
thanks @wojdyr - acknowledging your confirmation on this issue and thx for suggesting the workaround.

**Comment by rafaelhbarros** [comment] 2016-01-04 22:43
I ran the command a few hundred times (thanks to a script) and got no errors. Further instructions?

**Comment by rafaelhbarros** [comment] 2016-01-04 23:52
@flamingbear can you still reproduce the issue?

**Comment by flamingbear** [comment] 2016-01-04 23:55
Let me check

**Comment by flamingbear** [comment] 2016-01-05 00:09
Yes. I have a feeling it's closely related to:  https://github.com/Anaconda-Server/anaconda-client/issues/265

It may have something to do with existing packages.  For this project I have
1.0.0dev which fails as expected, and I bumped the version to 1.0.1dev which
does not fail.





```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.0dev/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.0dev-py35_0.tar.bz2 already exists ... removing
[ServerError] ('Internal server error', 500)
```

```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.0dev/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 ...
 uploaded 34 of 34Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/sedna
```

```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.0dev/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.0dev-py35_0.tar.bz2 already exists ... removing
[ServerError] ('Internal server error', 500)
vagrant@vslushycore:/tmp$
```

BUT  Works with "newly" created package

```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.1dev/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.1dev-py35_0.tar.bz2 already exists ... removing
 uploaded 34 of 34Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/sedna
```

```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.1dev/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.1dev-py35_0.tar.bz2 already exists ... removing
 uploaded 34 of 34Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/sedna
```

```
vagrant@vslushycore:/tmp$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.1dev/osx-64/sedna-1.0.1dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.1dev-py35_0.tar.bz2 already exists ... removing
 uploaded 34 of 34Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/sedna
```

**Comment by rafaelhbarros** [comment] 2016-01-05 20:38
I cannot reproduce this issue with old packages or new packages. I'll add some logs and after a new release (should happen by the end of the week) we can try this again.

Really bothering me that I can't pin-point the error.

**Comment by flamingbear** [comment] 2016-01-05 23:03
Cool, I will try my hardest not to delete the package that is currently broken.  Let me know when you want me to test again.

**Comment by wojdyr** [comment] 2016-01-05 23:27
What I wrote yesterday about downgrading is actually not true. I've seen the same problem later on with both client versions. But it wasn't happening every time, so as a workaround I just re-try upload if it fails in a script:
```
anaconda upload --force $f || \
anaconda upload --force $f
```
and with this uploads happen to work for me.

@rafaelhbarros: thanks for looking into it. If you have access to the server logs maybe you can check for status 500 there?

**Comment by rafaelhbarros** [comment] 2016-01-05 23:33
@wojdyr @flamingbear that's exactly why I'll add some more detailed logs onto the server in order to get a better insight when the issue happens.

**Comment by rafaelhbarros** [comment] 2016-01-12 19:31
@wojdyr @flamingbear alright, I rolled out a new version of anaconda.org yesterday. Some new logging is in place so if this happens, I'll get all the information I can. Can you please reproduce this issue one more time? I have hopes to catch it now.

**Comment by flamingbear** [comment] 2016-01-12 20:02
You should have something now:

```
vagrant@vslushycore:~$ !12
export ANACONDA_TOKEN=`sudo cat /home/vagrant/anaconda/anaconda.token`
vagrant@vslushycore:~$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.0dev/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 ...
 uploaded 34 of 34Kb: 100.00% ETA: 0.0 minutes


Upload(s) Complete

Package located at:
https://anaconda.org/nsidc/sedna

vagrant@vslushycore:~$ anaconda -t $ANACONDA_TOKEN upload -u nsidc /opt/miniconda/conda-bld/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 -c dev --force
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file nsidc/sedna/1.0.0dev/osx-64/sedna-1.0.0dev-py35_0.tar.bz2 ...
[WARNING] Distribution osx-64/sedna-1.0.0dev-py35_0.tar.bz2 already exists ... removing
[ServerError] ('Internal server error', 500)
vagrant@vslushycore:~$ echo date
date
vagrant@vslushycore:~$ date
Tue Jan 12 12:47:12 MST 2016
```

**Comment by rafaelhbarros** [comment] 2016-01-12 20:03
@flamingbear got it, thanks. Two good news: this is a backend fix, so nothing needs to change on your environment, and I know how to fix it.

**Comment by srossross** [comment] 2016-01-15 22:00
@rafaelhbarros should this be 'in-progress'?

**Comment by rafaelhbarros** [comment] 2016-01-22 17:47
@flamingbear a release was done today, can you please verify the issue no longer happens?

**Comment by flamingbear** [comment] 2016-01-22 19:12
Looks good to me.  Thanks!

**Comment by rafaelhbarros** [comment] 2016-01-22 19:13
Closing this issue as fixed. If it happens again, let me know.

**Closed by rafaelhbarros** 2016-01-22 19:13 UTC
Labels: bug
