### ISSUE TITLE
`anaconda upload` fails to upload package from Win64

### ISSUE THREAD

**Issue by wikiped** [Anaconda-Server/anaconda-client#222] opened 2015-10-31 17:31 UTC
While trying to upload a package with `anaconda upload` an error occurs: 

	D:\Anaconda\conda-bld\win-64>anaconda upload cchardet-1.0.0-py27_0.tar.bz2
	Using anaconda-server api site https://api.anaconda.org
	detecting package type ...
	conda
	extracting package attributes for upload ...
	done

	Uploading file User/cchardet/1.0.0/win-64/cchardet-1.0.0-py27_0.tar.bz2 ...
	 uploaded 0 of 80Kb: 0.00% ETA: 0.0 minutes[TypeError] cannot make memory view because object does not have the buffer interface
	Traceback (most recent call last):
	  File "D:\Anaconda\Scripts\anaconda-script.py", line 5, in <module>
		sys.exit(main())
	  File "D:\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 93, in main
		description=__doc__, version=version)
	  File "D:\Anaconda\lib\site-packages\binstar_client\scripts\cli.py", line 75, in binstar_main
		return args.main(args)
	  File "D:\Anaconda\lib\site-packages\binstar_client\commands\upload.py", line 203, in main
		callback=upload_print_callback(args))
	  File "D:\Anaconda\lib\site-packages\binstar_client\__init__.py", line 425, in upload
		s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
	  File "D:\Anaconda\lib\site-packages\requests\api.py", line 109, in post
		return request('post', url, data=data, json=json, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\api.py", line 50, in request
		response = session.request(method=method, url=url, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 468, in request
		resp = self.send(prep, **send_kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 576, in send
		r = adapter.send(request, **kwargs)
	  File "D:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
		timeout=timeout
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
		body=body, headers=headers)
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 353, in _make_request
		conn.request(method, url, **httplib_request_kw)
	  File "D:\Anaconda\lib\httplib.py", line 1053, in request
		self._send_request(method, url, body, headers)
	  File "D:\Anaconda\lib\httplib.py", line 1093, in _send_request
		self.endheaders(body)
	  File "D:\Anaconda\lib\httplib.py", line 1049, in endheaders
		self._send_output(message_body)
	  File "D:\Anaconda\lib\httplib.py", line 897, in _send_output
		self.send(message_body)
	  File "D:\Anaconda\lib\httplib.py", line 866, in send
		self.sock.sendall(datablock)
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 216, in sendall
		data = memoryview(data)
	TypeError: cannot make memory view because object does not have the buffer interface

Current conda install:

				 platform : win-64
			conda version : 3.18.3
	  conda-build version : 1.18.1
		   python version : 2.7.10.final.0
		 requests version : 2.8.1
		 root environment : D:\Anaconda  (writable)
	  default environment : D:\Anaconda
		 envs directories : D:\Anaconda\envs
			package cache : D:\Anaconda\pkgs
			 channel URLs : https://repo.continuum.io/pkgs/free/win-64/
							https://repo.continuum.io/pkgs/free/noarch/
							https://repo.continuum.io/pkgs/pro/win-64/
							https://repo.continuum.io/pkgs/pro/noarch/
							https://conda.anaconda.org/User/win-64/
							https://conda.anaconda.org/User/noarch/
			  config file : C:\Users\User\.condarc
		is foreign system : False

**Comment by srossross** [comment] 2015-11-01 18:11
@wikiped the looks like it is coming from the `requests` library. What version of requests do you have installed? (use `conda list`).  I will try and reproduce this error.

**Comment by wikiped** [comment] 2015-11-01 18:46
requests version : 2.8.1 (latest)

I thought so too...
So reinstalled it, but still getting error.

**Comment by srossross** [comment] 2015-11-02 15:49
@wikiped can you try after downgrading requests:

```
conda install requests=2.7
```

**Comment by wikiped** [comment] 2015-11-02 17:49
Downgraded requests to 2.7 and upload works fine again without any errors.

**Comment by srossross** [comment] 2015-11-12 02:54
Thanks @wikiped I don't think that the root error is fixed. I have had this error with `requests 2.7` as well.  We are still working on a permanent fix.

**Comment by dsludwig** [comment] 2015-11-13 23:08
kennethreitz/requests#2818
shazow/urllib3#719

Based on these two issues, either this will be resolved when a new version of requests is released with an upgraded urllib3 that has the `memoryview` call removed, or we will have to identify where we are letting `unicode` objects into the `requests` api.

**Comment by dsludwig** [comment] 2015-11-16 17:49
To reproduce on OS X: `conda install ndg-httpsclient pyasn1 PyOpenSSL` and then try to upload a package.

**Comment by srossross** [comment] 2015-11-24 21:06
This will make it into the next release. We will close the issue when that release makes it out.

**Comment by dsludwig** [comment] 2015-12-04 19:56
This issue has been fixed in the latest release. There is still an outstanding issue with requests 2.8, but they are working on releasing 2.9, and for now you can downgrade to 2.7.

**Comment by malev** [comment] 2015-12-07 21:40
This is happening again in the `osx` worker
```
1254[Build Targets]
1255anaconda  -q -t $TOKEN upload --force --user Anaconda-Notebook --package nbwrapper  --channel dev /Users/binstar/miniconda/conda-bld/osx-64/*.tar.bz2 --build-id 5.2
1256Using anaconda-server api site https://api.anaconda.org
1257[WARNING] Distribution osx-64/nbwrapper-0.0.1dev-py27_0.tar.bz2 already exists ... removing
1258[ERROR] 
1259Traceback (most recent call last):
1260  File "/Users/binstar/miniconda/bin/anaconda", line 6, in <module>
1261    sys.exit(main())
1262  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 82, in main
1263    description=__doc__, version=version)
1264  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
1265    return args.main(args)
1266  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 203, in main
1267    callback=upload_print_callback(args))
1268  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 425, in upload
1269    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
1270  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 109, in post
1271    return request('post', url, data=data, json=json, **kwargs)
1272  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
1273    response = session.request(method=method, url=url, **kwargs)
1274  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
1275    resp = self.send(prep, **send_kwargs)
1276  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
1277    r = adapter.send(request, **kwargs)
1278  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
1279    timeout=timeout
1280  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
1281    body=body, headers=headers)
1282  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
1283    conn.request(method, url, **httplib_request_kw)
1284  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1053, in request
1285    self._send_request(method, url, body, headers)
1286  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1093, in _send_request
1287    self.endheaders(body)
1288  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1049, in endheaders
1289    self._send_output(message_body)
1290  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 897, in _send_output
1291    self.send(message_body)
1292  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 866, in send
1293    self.sock.sendall(datablock)
1294  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
1295    data = memoryview(data)
1296TypeError: cannot make memory view because object does not have the buffer interface
1297command exited with status 1
```

**Comment by ContinuumJira** [comment] 2015-12-08 21:24
@malev - in certain scenarios, there's a workaround - can you check with
Derek

On Mon, Dec 7, 2015 at 3:40 PM, Marcos Vanetta <notifications@github.com>
wrote:

> This is happening again in the osx worker
>
> 1254[Build Targets]
> 1255anaconda  -q -t $TOKEN upload --force --user Anaconda-Notebook --package nbwrapper  --channel dev /Users/binstar/miniconda/conda-bld/osx-64/*.tar.bz2 --build-id 5.2
> 1256Using anaconda-server api site https://api.anaconda.org
> 1257[WARNING] Distribution osx-64/nbwrapper-0.0.1dev-py27_0.tar.bz2 already exists ... removing
> 1258[ERROR]
> 1259Traceback (most recent call last):
> 1260  File "/Users/binstar/miniconda/bin/anaconda", line 6, in <module>
> 1261    sys.exit(main())
> 1262  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 82, in main
> 1263    description=__doc__, version=version)
> 1264  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
> 1265    return args.main(args)
> 1266  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 203, in main
> 1267    callback=upload_print_callback(args))
> 1268  File "/Users/binstar/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 425, in upload
> 1269    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, timeout=10 * 60 * 60, headers=headers)
> 1270  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 109, in post
> 1271    return request('post', url, data=data, json=json, **kwargs)
> 1272  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
> 1273    response = session.request(method=method, url=url, **kwargs)
> 1274  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
> 1275    resp = self.send(prep, **send_kwargs)
> 1276  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
> 1277    r = adapter.send(request, **kwargs)
> 1278  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
> 1279    timeout=timeout
> 1280  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
> 1281    body=body, headers=headers)
> 1282  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
> 1283    conn.request(method, url, **httplib_request_kw)
> 1284  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1053, in request
> 1285    self._send_request(method, url, body, headers)
> 1286  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1093, in _send_request
> 1287    self.endheaders(body)
> 1288  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 1049, in endheaders
> 1289    self._send_output(message_body)
> 1290  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 897, in _send_output
> 1291    self.send(message_body)
> 1292  File "/Users/binstar/miniconda/lib/python2.7/httplib.py", line 866, in send
> 1293    self.sock.sendall(datablock)
> 1294  File "/Users/binstar/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
> 1295    data = memoryview(data)
> 1296TypeError: cannot make memory view because object does not have the buffer interface
> 1297command exited with status 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-client/issues/222#issuecomment-162672596>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by ijstokes** [comment] 2015-12-09 22:03
Who is @ContinuumJira ? As I said in FD, it is impossible that there is no way to do an HTTP POST in Python using `requests`.  That not working would be a super fundamental failure of the entire package.  There must be some way we can adapt the call we're making so it will work.

**Comment by dsludwig** [comment] 2015-12-23 19:07
http://docs.python-requests.org/en/latest/community/updates/#release-and-version-history

Requests 2.9.1 has been released with a fix to the upload code. Upgrading your version of the library should resolve all instances of this issue.

**Closed by dsludwig** 2015-12-23 19:07 UTC
Labels: bug, Source - Client Requested
