### ISSUE TITLE
Dupe: anaconda upload -u (user) option should be -c (channel)

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-client#259] opened 2015-12-10 02:32 UTC
It is odd to do:

```bash
anaconda upload -u foo barpkg.tar.bz2
```

to upload `barpkg` into the "user" space specified by `-u` and then (perhaps just moments later) to do:

```bash
conda install -c foo barpkg
```

I would like to suggest that Anaconda Client instead make use of `-c` (channel) instead of `-u` (user)

**Comment by stephenakearns** [comment] 2015-12-11 17:36
Duplicate of Anaconda-Server/Anaconda-server#559 which is in progress in current epic.

**Closed by stephenakearns** 2015-12-11 17:36 UTC
