### ISSUE TITLE
ConnectionError stacktrace when failling to connect to the API endpoint.

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Server/anaconda-client#195] opened 2015-07-31 18:28 UTC
Stack trace when trying to get a custom AS running and connecting to the api endpoint:
```
Using binstar api site https://api.ac.demo.continuum.io
[ConnectionError] ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')) 
Traceback (most recent call last):
  File "/Users/bkreider/test/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/Users/bkreider/test/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/bkreider/test/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/bkreider/test/lib/python2.7/site-packages/binstar_client/commands/authorizations.py", line 124, in main
    data = binstar.authentication()
  File "/Users/bkreider/test/lib/python2.7/site-packages/binstar_client/__init__.py", line 105, in authentication
    res = self.session.get(url)
  File "/Users/bkreider/test/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/bkreider/test/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bkreider/test/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bkreider/test/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
```

**Comment by malev** [comment] 2015-07-31 18:48
Looks like the URL is not the right one. try `https://ac.demo.continuum.io/api`

**Comment by bkreider** [comment] 2015-08-01 02:16
Yes.  But why is there a massive stack trace being spewed to the user.  Why doesn't the error message say that instead of 20 lines of gobblygook?

**Comment by malev** [comment] 2015-08-10 21:31
good point

**Comment by stephenakearns** [comment] 2015-10-30 22:24
Closing - this is a duplicate of #206

**Closed by stephenakearns** 2015-10-30 22:24 UTC
Labels: bug
