### ISSUE TITLE
Add list of released files, their build numbers, and channels when deleting a package

### ISSUE THREAD

**Issue by tswicegood** [Anaconda-Server/anaconda-client#86] opened 2014-06-17 20:13 UTC
Currently the warning reads along the lines of:

    Are you sure you want to remove the package release tswicegood/awesome/1.0.0 ? (and all files under it?) [y|N]:

Would be nice if it acted like `conda` and gave me a full list of what was about to happen.

**Comment by stephenakearns** [comment] 2015-10-30 19:42
Duplicate of #559 - closing

**Closed by stephenakearns** 2015-10-30 19:42 UTC
Labels: enhancement
